uncomment step

diff --git a/.github/workflows/check-ui-code-coverage.yaml b/.github/workflows/check-ui-code-coverage.yaml
--- a/.github/workflows/check-ui-code-coverage.yaml
+++ b/.github/workflows/check-ui-code-coverage.yaml
@@ -93,19 +93,19 @@ jobs:
           git checkout main -- jest.config.json
           cat jest.config.json
 
-      # - name: Extract coverage threshold from main branch
-      #   id: extract-min-code-coverage-from-main
-      #   run: |
-      #     thresholdFile=jest.config.json
-      #     if [ -f "$thresholdFile" ]; then
-      #       echo "Threshold file found"
-      #       threshold=$(jq '.coverageThreshold.global.lines' $thresholdFile)
-      #       echo "Threshold: $threshold"
-      #       echo "threshold=$threshold" >> $GITHUB_OUTPUT
-      #     else
-      #       echo "Threshold file not found"
-      #       exit 1
-      #     fi
+      - name: Extract coverage threshold from main branch
+        id: extract-min-code-coverage-from-main
+        run: |
+          thresholdFile=jest.config.json
+          if [ -f "$thresholdFile" ]; then
+            echo "Threshold file found"
+            threshold=$(jq '.coverageThreshold.global.lines' $thresholdFile)
+            echo "Threshold: $threshold"
+            echo "threshold=$threshold" >> $GITHUB_OUTPUT
+          else
+            echo "Threshold file not found"
+            exit 1
+          fi
 
       # - name: Modify coverage threshold
       #   id: modify-coverage-threshold
