test new workflow

diff --git a/.github/workflows/check-code-coverage.yaml b/.github/workflows/check-code-coverage.yaml
--- a/.github/workflows/check-code-coverage.yaml
+++ b/.github/workflows/check-code-coverage.yaml
@@ -2,19 +2,23 @@ name: Check code coverage
 
 on:
   pull_request:
-    branches:
-      - main
+    # branches:
+    #   - main
+    paths:
+      - 'frontend/main-ui/**'
+      - 'frontend/customers-page/**'
+      - 'frontend/competitions-page/**'
   workflow_dispatch:
 
 env:
   CODE_COVERAGE_MODIFIER: 2
   RAMPING_CODE_COVERAGE_CAP: 90
+  MAIN_UI_PATH: frontend/main-ui/
 
 jobs:
-  check-code-coverage:
-    # if: github.event.action != 'closed'
+  check-code-coverage-on-main-ui:
+    if: contains(github.event.pull_request.changed_files, 'frontend/main-ui/')
     runs-on: ubuntu-latest
-
     steps:
       - name: Check out the code
         uses: actions/checkout@v4
@@ -30,87 +34,164 @@ jobs:
         with:
           node-version: '18'
 
-      - name: Extract coverage threshold from main branch
-        id: extract-min-code-coverage-from-main
-        run: |
-          thresholdFile=jest.config.json
-          if [ -f "$thresholdFile" ]; then
-            echo "Threshold file found"
-            threshold=$(jq '.coverageThreshold.global.lines' $thresholdFile)
-            echo "Threshold: $threshold"
-            echo "threshold=$threshold" >> $GITHUB_OUTPUT
-          else
-            echo "Threshold file not found"
-            exit 1
-          fi
-
-      - name: Modify coverage threshold
-        id: modify-coverage-threshold
-        run: |
-          current_threshold=${{ steps.extract-min-code-coverage-from-main.outputs.threshold }}
-          new_threshold=$((current_threshold + $CODE_COVERAGE_MODIFIER))
-          echo "New Threshold: $new_threshold"
-
-          if [ "$new_threshold" -gt "$RAMPING_CODE_COVERAGE_CAP" ]; then
-            new_threshold=$RAMPING_CODE_COVERAGE_CAP
-          fi
-          echo "New Threshold (after cap): $new_threshold"
-
-          temp_file=jest.config.tmp
-
-          # Update the jest.config.json file with the new threshold
-          jq --argjson new_threshold "$new_threshold" '.coverageThreshold.global.lines = $new_threshold' jest.config.json > $temp_file
-          mv $temp_file jest.config.json
-
-          echo "new_threshold=$new_threshold" >> $GITHUB_OUTPUT
-
-        # # Update the jest.config.json file with the new threshold
-        # jq --argjson new_threshold "$new_threshold" '.coverageThreshold.global.lines = $new_threshold' jest.config.json > jest.config.tmp && mv jest.config.tmp jest.config.json
-        # echo "new_threshold=$new_threshold" >> $GITHUB_OUTPUT
-
-      - name: Output required line coverage
-        run: |
-          echo "Current Jest coverage threshold for lines is ${{ steps.extract-min-code-coverage-from-main.outputs.threshold }}%"
-          echo "Required line coverage is ${{ steps.modify-coverage-threshold.outputs.new_threshold }}%"
-
-      - name: Install dependencies
-        run: npm install
-
-      - name: View jest.config.json
-        run: cat jest.config.json
-
-      - name: Run coverage and print results
-        run: |
-          npm run coverage
-
-      - name: Read and print coverage summary
-        id: pull-request-coverage
-        run: |
-          coverageFile=coverage/coverage-summary.json
-          if [ -f "$coverageFile" ]; then
-            echo "Coverage file found"
-            cat $coverageFile
-            totalCoverage=$(jq '.total.lines.pct' $coverageFile)
-            echo "Total line coverage: $totalCoverage%"
-            echo "totalCoverage=$totalCoverage" >> $GITHUB_OUTPUT
-          else
-            echo "Coverage file not found!"
-            exit 1
-          fi
-
-      - name: Print total coverage and threshold
-        run: |
-          echo "The line coverage on the Pull Request is ${{ steps.pull-request-coverage.outputs.totalCoverage }}%"
-          echo "The line coverage threshold on main is ${{ steps.extract-min-code-coverage-from-main.outputs.threshold }}%"
-          echo "The required line coverage threshold is ${{ steps.modify-coverage-threshold.outputs.new_threshold }}%"
-
-      # - name: Check coverage meets threshold
+      # - name: Extract coverage threshold from main branch
+      #   id: extract-min-code-coverage-from-main
       #   run: |
-      #     totalCoverage=${{ steps.pull-request-coverage.outputs.totalCoverage }}
-      #     newThreshold=${{ steps.modify-coverage-threshold.outputs.new_threshold }}
-      #     if (( $(echo "$totalCoverage < $newThreshold" | bc -l) )); then
-      #       echo "Total coverage $totalCoverage% is less than the required threshold $newThreshold%"
-      #       exit 1
+      #     thresholdFile=jest.config.json
+      #     if [ -f "$thresholdFile" ]; then
+      #       echo "Threshold file found"
+      #       threshold=$(jq '.coverageThreshold.global.lines' $thresholdFile)
+      #       echo "Threshold: $threshold"
+      #       echo "threshold=$threshold" >> $GITHUB_OUTPUT
       #     else
-      #       echo "Total coverage $totalCoverage% meets or exceeds the required threshold $newThreshold%"
+      #       echo "Threshold file not found"
+      #       exit 1
       #     fi
+
+      # - name: Modify coverage threshold
+      #   id: modify-coverage-threshold
+      #   run: |
+      #     current_threshold=${{ steps.extract-min-code-coverage-from-main.outputs.threshold }}
+      #     new_threshold=$((current_threshold + $CODE_COVERAGE_MODIFIER))
+      #     echo "New Threshold: $new_threshold"
+
+      #     if [ "$new_threshold" -gt "$RAMPING_CODE_COVERAGE_CAP" ]; then
+      #       new_threshold=$RAMPING_CODE_COVERAGE_CAP
+      #     fi
+      #     echo "New Threshold (after cap): $new_threshold"
+
+      #     temp_file=jest.config.tmp
+
+      #     # Update the jest.config.json file with the new threshold
+      #     jq --argjson new_threshold "$new_threshold" '.coverageThreshold.global.lines = $new_threshold' jest.config.json > $temp_file
+      #     mv $temp_file jest.config.json
+
+      #     echo "new_threshold=$new_threshold" >> $GITHUB_OUTPUT
+
+      # - name: Output required line coverage
+      #   run: |
+      #     echo "Current Jest coverage threshold for lines is ${{ steps.extract-min-code-coverage-from-main.outputs.threshold }}%"
+      #     echo "Required line coverage is ${{ steps.modify-coverage-threshold.outputs.new_threshold }}%"
+
+      # - name: Install dependencies
+      #   run: npm install
+
+      # - name: View jest.config.json
+      #   run: cat jest.config.json
+
+      # - name: Run coverage and print results
+      #   run: |
+      #     npm run coverage
+
+      # - name: Read and print coverage summary
+      #   id: pull-request-coverage
+      #   run: |
+      #     coverageFile=coverage/coverage-summary.json
+      #     if [ -f "$coverageFile" ]; then
+      #       echo "Coverage file found"
+      #       cat $coverageFile
+      #       totalCoverage=$(jq '.total.lines.pct' $coverageFile)
+      #       echo "Total line coverage: $totalCoverage%"
+      #       echo "totalCoverage=$totalCoverage" >> $GITHUB_OUTPUT
+      #     else
+      #       echo "Coverage file not found!"
+      #       exit 1
+      #     fi
+
+      # - name: Print total coverage and threshold
+      #   run: |
+      #     echo "The line coverage on the Pull Request is ${{ steps.pull-request-coverage.outputs.totalCoverage }}%"
+      #     echo "The line coverage threshold on main is ${{ steps.extract-min-code-coverage-from-main.outputs.threshold }}%"
+      #     echo "The required line coverage threshold is ${{ steps.modify-coverage-threshold.outputs.new_threshold }}%"
+
+  # check-code-coverage:
+  #   runs-on: ubuntu-latest
+
+  #   steps:
+  #     - name: Check out the code
+  #       uses: actions/checkout@v4
+
+  #     - name: Fetch main branch
+  #       run: git fetch origin main:main
+
+  #     - name: Checkout main branch jest.config.json
+  #       run: git checkout main -- jest.config.json
+
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: '18'
+
+  #     - name: Extract coverage threshold from main branch
+  #       id: extract-min-code-coverage-from-main
+  #       run: |
+  #         thresholdFile=jest.config.json
+  #         if [ -f "$thresholdFile" ]; then
+  #           echo "Threshold file found"
+  #           threshold=$(jq '.coverageThreshold.global.lines' $thresholdFile)
+  #           echo "Threshold: $threshold"
+  #           echo "threshold=$threshold" >> $GITHUB_OUTPUT
+  #         else
+  #           echo "Threshold file not found"
+  #           exit 1
+  #         fi
+
+  #     - name: Modify coverage threshold
+  #       id: modify-coverage-threshold
+  #       run: |
+  #         current_threshold=${{ steps.extract-min-code-coverage-from-main.outputs.threshold }}
+  #         new_threshold=$((current_threshold + $CODE_COVERAGE_MODIFIER))
+  #         echo "New Threshold: $new_threshold"
+
+  #         if [ "$new_threshold" -gt "$RAMPING_CODE_COVERAGE_CAP" ]; then
+  #           new_threshold=$RAMPING_CODE_COVERAGE_CAP
+  #         fi
+  #         echo "New Threshold (after cap): $new_threshold"
+
+  #         temp_file=jest.config.tmp
+
+  #         # Update the jest.config.json file with the new threshold
+  #         jq --argjson new_threshold "$new_threshold" '.coverageThreshold.global.lines = $new_threshold' jest.config.json > $temp_file
+  #         mv $temp_file jest.config.json
+
+  #         echo "new_threshold=$new_threshold" >> $GITHUB_OUTPUT
+
+  #       # # Update the jest.config.json file with the new threshold
+  #       # jq --argjson new_threshold "$new_threshold" '.coverageThreshold.global.lines = $new_threshold' jest.config.json > jest.config.tmp && mv jest.config.tmp jest.config.json
+  #       # echo "new_threshold=$new_threshold" >> $GITHUB_OUTPUT
+
+  #     - name: Output required line coverage
+  #       run: |
+  #         echo "Current Jest coverage threshold for lines is ${{ steps.extract-min-code-coverage-from-main.outputs.threshold }}%"
+  #         echo "Required line coverage is ${{ steps.modify-coverage-threshold.outputs.new_threshold }}%"
+
+  #     - name: Install dependencies
+  #       run: npm install
+
+  #     - name: View jest.config.json
+  #       run: cat jest.config.json
+
+  #     - name: Run coverage and print results
+  #       run: |
+  #         npm run coverage
+
+  #     - name: Read and print coverage summary
+  #       id: pull-request-coverage
+  #       run: |
+  #         coverageFile=coverage/coverage-summary.json
+  #         if [ -f "$coverageFile" ]; then
+  #           echo "Coverage file found"
+  #           cat $coverageFile
+  #           totalCoverage=$(jq '.total.lines.pct' $coverageFile)
+  #           echo "Total line coverage: $totalCoverage%"
+  #           echo "totalCoverage=$totalCoverage" >> $GITHUB_OUTPUT
+  #         else
+  #           echo "Coverage file not found!"
+  #           exit 1
+  #         fi
+
+  #     - name: Print total coverage and threshold
+  #       run: |
+  #         echo "The line coverage on the Pull Request is ${{ steps.pull-request-coverage.outputs.totalCoverage }}%"
+  #         echo "The line coverage threshold on main is ${{ steps.extract-min-code-coverage-from-main.outputs.threshold }}%"
+  #         echo "The required line coverage threshold is ${{ steps.modify-coverage-threshold.outputs.new_threshold }}%"
