update script

diff --git a/.github/workflows/check-code-coverage.yaml b/.github/workflows/check-code-coverage.yaml
--- a/.github/workflows/check-code-coverage.yaml
+++ b/.github/workflows/check-code-coverage.yaml
@@ -51,8 +51,9 @@ jobs:
           new_threshold=$((current_threshold + $CODE_COVERAGE_MODIFIER))
           echo "New Threshold: $new_threshold"
           # Update the jest.config.json file with the new threshold
-          jq --argjson new_threshold "$new_threshold" '.coverageThreshold.global.lines = $new_threshold' jest.config.json > jest.config.tmp && mv jest.config.tmp jest.config.json
           echo "new_threshold=$new_threshold" >> $GITHUB_OUTPUT
+
+        # jq --argjson new_threshold "$new_threshold" '.coverageThreshold.global.lines = $new_threshold' jest.config.json > jest.config.tmp && mv jest.config.tmp jest.config.json
 
       - name: Output required line coverage
         run: |
@@ -86,3 +87,14 @@ jobs:
           echo "The line coverage on the Pull Request is ${{ steps.pull-request-coverage.outputs.totalCoverage }}%"
           echo "The line coverage threshold on main is ${{ steps.extract-min-code-coverage-from-main.outputs.threshold }}%"
           echo "The required line coverage threshold is ${{ steps.modify-coverage-threshold.outputs.new_threshold }}%"
+
+      - name: Check coverage meets threshold
+        run: |
+          totalCoverage=${{ steps.pull-request-coverage.outputs.totalCoverage }}
+          newThreshold=${{ steps.modify-coverage-threshold.outputs.new_threshold }}
+          if (( $(echo "$totalCoverage < $newThreshold" | bc -l) )); then
+            echo "Total coverage $totalCoverage% is less than the required threshold $newThreshold%"
+            exit 1
+          else
+            echo "Total coverage $totalCoverage% meets or exceeds the required threshold $newThreshold%"
+          fi
