update script

diff --git a/.github/workflows/code-coverage.yaml b/.github/workflows/code-coverage.yaml
--- a/.github/workflows/code-coverage.yaml
+++ b/.github/workflows/code-coverage.yaml
@@ -49,25 +49,41 @@ jobs:
         run: |
           npm run coverage
 
-      - name: Read and print coverage summary
+      - name: Read coverage threshold
+        id: read-threshold
+        run: |
+          THRESHOLD=$(cat jest.config.json | jq '.coverageThreshold.global.lines')
+          echo "coverage-threshold=$THRESHOLD" >> $GITHUB_ENV
+
+      - name: Check coverage
         id: coverage
         run: |
-          coverageFile=coverage/coverage-summary.json
-          if [ -f "$coverageFile" ]; then
-            echo "Coverage file found"
-            cat $coverageFile
-            totalCoverage=$(jq '.total.lines.pct' $coverageFile)
-            echo "Total line coverage: $totalCoverage%"
-            echo "::set-output name=coverage::$totalCoverage"
-          else
-            echo "Coverage file not found!"
+          COVERAGE=$(jq .total.lines.pct < coverage/coverage-summary.json)
+          echo "Current coverage: $COVERAGE%"
+          if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
+            echo "Coverage is below $THRESHOLD%"
             exit 1
           fi
 
-      - name: Print total coverage and threshold
-        run: |
-          echo "The total coverage is ${{ steps.coverage.outputs.coverage }}%"
-          echo "The line coverage threshold is ${{ steps.extract-min-code-coverage-from-main.outputs.threshold }}%"
+      # - name: Read and print coverage summary
+      #   id: coverage
+      #   run: |
+      #     coverageFile=coverage/coverage-summary.json
+      #     if [ -f "$coverageFile" ]; then
+      #       echo "Coverage file found"
+      #       cat $coverageFile
+      #       totalCoverage=$(jq '.total.lines.pct' $coverageFile)
+      #       echo "Total line coverage: $totalCoverage%"
+      #       echo "::set-output name=coverage::$totalCoverage"
+      #     else
+      #       echo "Coverage file not found!"
+      #       exit 1
+      #     fi
+
+      # - name: Print total coverage and threshold
+      #   run: |
+      #     echo "The total coverage is ${{ steps.coverage.outputs.coverage }}%"
+      #     echo "The line coverage threshold is ${{ steps.extract-min-code-coverage-from-main.outputs.threshold }}%"
 
       # - name: Calculate new threshold
       #   id: calculate-new-threshold
