update script

diff --git a/.github/workflows/code-coverage.yaml b/.github/workflows/code-coverage.yaml
--- a/.github/workflows/code-coverage.yaml
+++ b/.github/workflows/code-coverage.yaml
@@ -56,31 +56,32 @@ jobs:
       - name: Output coverage threshold
         run: |
           echo "Current Jest coverage threshold for lines is ${{ steps.extract-min-code-coverage-from-main.outputs.threshold }}"
-          echo "Required line coverage is ${{ steps.modify-coverage-threshold.outputs.threshold }}"
+          echo "Required line coverage is ${{ steps.modify-coverage-threshold.outputs.new_threshold }}"
 
-      # - name: Install dependencies
-      #   run: npm install
+      - name: Install dependencies
+        run: npm install
 
-      # - name: Run coverage and print results
-      #   run: |
-      #     npm run coverage
+      - name: Run coverage and print results
+        run: |
+          npm run coverage
 
-      # - name: Read and print coverage summary
-      #   id: coverage
-      #   run: |
-      #     coverageFile=coverage/coverage-summary.json
-      #     if [ -f "$coverageFile" ]; then
-      #       echo "Coverage file found"
-      #       cat $coverageFile
-      #       totalCoverage=$(jq '.total.lines.pct' $coverageFile)
-      #       echo "Total line coverage: $totalCoverage%"
-      #       echo "::set-output name=coverage::$totalCoverage"
-      #     else
-      #       echo "Coverage file not found!"
-      #       exit 1
-      #     fi
+      - name: Read and print coverage summary
+        id: coverage
+        run: |
+          coverageFile=coverage/coverage-summary.json
+          if [ -f "$coverageFile" ]; then
+            echo "Coverage file found"
+            cat $coverageFile
+            totalCoverage=$(jq '.total.lines.pct' $coverageFile)
+            echo "Total line coverage: $totalCoverage%"
+            echo "::set-output name=coverage::$totalCoverage"
+          else
+            echo "Coverage file not found!"
+            exit 1
+          fi
 
-      # - name: Print total coverage and threshold
-      #   run: |
-      #     echo "The total coverage is ${{ steps.coverage.outputs.coverage }}%"
-      #     echo "The line coverage threshold is ${{ steps.extract-min-code-coverage-from-main.outputs.threshold }}%"
+      - name: Print total coverage and threshold
+        run: |
+          echo "The total coverage is ${{ steps.coverage.outputs.coverage }}%"
+          echo "The line coverage threshold is ${{ steps.extract-min-code-coverage-from-main.outputs.threshold }}%"
+          echo "The modified line coverage threshold is ${{ steps.modify-coverage-threshold.outputs.new_threshold }}%"
