update script

diff --git a/.github/workflows/code-coverage.yaml b/.github/workflows/code-coverage.yaml
--- a/.github/workflows/code-coverage.yaml
+++ b/.github/workflows/code-coverage.yaml
@@ -88,7 +88,12 @@ jobs:
 
       - name: Compare pull request coverage with modified requirement
         run: |
-          pr_coverage = ${{ steps.coverage.outputs.coverage }}
-          required_coverage = ${{ steps.modify-coverage-threshold.outputs.new_threshold }}
-          echo "PR $pr_coverage"
-          echo "Required $required_coverage"
+          pr_coverage=${{ steps.coverage.outputs.coverage }}
+          required_coverage=${{ steps.modify-coverage-threshold.outputs.new_threshold }}
+          echo "Comparing PR coverage (${pr_coverage}%) with the required coverage (${required_coverage}%)"
+          if ($(echo "$pr_coverage < $required_coverage"); then
+            echo "Coverage on pull request (${pr_coverage}%) is less than the required threshold (${required_coverage}%). Failing the job."
+            exit 1
+          else
+            echo "Coverage on pull request (${pr_coverage}%) meets the required threshold (${required_coverage}%)."
+          fi
